### ISSUE TITLE
append instead of replace

### ISSUE THREAD

**Issue by ctf0** [gabrielbarker/ColorCode#24]
atm on theme generation both
- editor.tokenColorCustomizations
- workbench.colorCustomizations

will be cleared.

it would be better to keep them as you go through the new colors generated by the ext

**Comment by rubysdeadname** [comment]
You're right @ctf0 
Thank you for bringing this to my attention, I'll have a look soon

**Comment by rubysdeadname** [comment]
I believe I have resolved the problem in the above PR. I will release a patch version of the ext soon. Thanks again @ctf0

**Comment by ctf0** [comment]
btw u dont need to clone, modify the object and set with update, dont worry about mutation of the original setting

**Comment by rubysdeadname** [comment]
The object is of type WorkspaceConfiguration which is apparently readonly so, without the clone, whenever I tried to modify 'workbenchConfig' I got an error

**Comment by ctf0** [comment]
check my ext terminal-themes, it does exactly that

**Comment by rubysdeadname** [comment]
You're right, it does do the same thing, thank you. I _think_ the reason that your approach is different to mine is that: 

1. My extension file is a typescript file, so 'vscode.workspace.getConfiguration()' returns a readonly object. Since your extension is pure js the concept of readonly doesn't really exist
2. Your method 'clearOldStyles' takes the configuration and returns a "new" object/array through the reduce function so even if it was readonly you would be effectively making a new object

I'm still not totally happy with the JSON.parse(JSON.stringify(...)) approach though and I'll try to think of a better solution

**Comment by rubysdeadname** [comment]
A better way of cloning is maybe replacing `JSON.parse(JSON.stringify(workbench))` with `{...workbench}`

**Comment by ctf0** [comment]
am not sure if array spread apply to objects, what i had in mind is 
- get the current config 
```js
let current = vscode.workspace.getConfiguration("workbench.colorCustomizations");
```
- add ur stuff
```
current["[color mode]"] = {...} // the styles
```
- update the settings
```
await vscode.workspace.getConfiguration().update('workbench.colorCustomizations', current, true)
```

the difference between color mode and terminal themes, is that u have a specific key that only u use it `"[color mode]"` so you can do all ur stuff on that key without worrying about anything else,
while in my case am applying to the main key `workbench.colorCustomizations` so i've to filter out old added styles b4 i add new ones to avoid having duplicate keys.

the read only of `workbench.colorCustomizations` means that u cant mutate it directly once u fetched it, but it doesn't mean u cant change it through other ways :eyes:

**Comment by rubysdeadname** [comment]
Ok I think I understand what you're saying. So I tried that approach and on step 2 I get the error of not being able to change
`current["[ColorCode]"]` 
because it's readonly and `current` is a reference to the actual settings. So I could instead try and just update `current` by doing 
`current.update("[ColorCode]", {...})`
The problem here is that `current`, i.e.
`vscode.workspace.getConfiguration("workbench.colorCustomizations")` is a standard field on the WorkspaceConfiguration, however `[ColorCode]` isn't, so I end up with `"workbench.colorCustomizations.[ColorCode]": { ... }` 
in the settings.json, when I actually want 
`"workbench.colorCustomizations { [ColorCode]":  { ... }  }`

As far as I can tell, I can only call `get` and `update` on `current` because of it's type. If I want to update it then I need to get the current colorCustomizations and modify them, which means I have to clone colorCustomizations as it is readonly.

I'm struggling to think of a better way to do this

**Comment by ctf0** [comment]
ok, I'll fork it to do some testing and will get back to you

**Comment by ctf0** [comment]
check https://github.com/ctf0/ColorCode/commit/084ee48c5a7f7e9f27d1bbd298a0ad35dbcf2009#diff-45327f86d4438556066de133327f4ca2

**Comment by rubysdeadname** [comment]
This looks great, nice work, I'm gonna make a couple of comments on that commit and then could you make a PR to my develop branch? Thanks

**Comment by ctf0** [comment]
sure

**Comment by rubysdeadname** [comment]
Thanks a lot for all your help! I've made some cosmetic changes to the ext as well and I will release them and your changes in v1.1.0  very soon
